### ISSUE TITLE
Methods with SubArrays

### ISSUE THREAD

**Issue by p-zubieta** [KristofferC/Pardiso.jl#11]
It would be nice if the methods would work also for `SubArray`s. Would defining them for `StridedVecOrMat` instead of `VecOrMat work or there is a limitation on Pardiso side?

**Comment by KristofferC** [comment]
It would probably work. Try it and report back :)

**Comment by pablosanjose** [comment]
Doing that seems to work, but doesn't quite. Take `A * X = B`. If your RHS `B` is a view of a `Vector`, and you widen the signatures to allow `StridedVecOrMat` it does work. However, if `B` is a view of a `Matrix`, say, the first column of `X` is correct, but the rest are not. I assume it is because the view is then not contiguous in memory.

What would be the correct way to solve this?
[My interest here is to get Pardiso working with ArnoldiMethods to get interior eigenvalues]

**Comment by KristofferC** [comment]
We could make it `StridedVecOrMat` and check that the first stride is `1`?

**Comment by pablosanjose** [comment]
Done. The PR #43 throws an error if the stride is not right.

**Comment by KristofferC** [comment]
Fixed.
